accounts/urls.py
from django.urls import path
from . import views

from django.contrib.auth import views as auth_views

app_name = 'acocounts'

urlpatterns = [

  path('signup/',
      views.SignUpView.as_view(),
       name='signup'),

  path('signup_success/',
      views.SignUpSuccessView.as_view(),
      name='signup_success'),

  path('login/', 
       auth_views.LoginView.as_view(template_name='login.html'),
       name='login'),

  path('logout/', 
       auth_views.LogoutView.as_view(template_name='logout.html'),
       name='logout'
       ),
  
]

caloriecraft/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

from django.conf import settings
from django.conf.urls.static import static


#URLconfのURLパターンを逆引きできるようにアプリ名を登録
app_name = 'caloriecraft'

#URLパターンを登録するためのリスト
urlpatterns = [
    
    path('', views.IndexView.as_view(), name='index'),
    path('search/', views.search, name='search'),
    path('post/', views.CreateRecipeView.as_view(), name='post'),
    path('post_done/', views.PostSuccessView.as_view(), name='post_done'),


    #
    #
    #
#    path('caloriecraft-detail/<int:pk>/', views.CalorieCraftDetail.as_view(), name='caloriecraft-detail'),
]

urlpatterns += static(

    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

caloriecraftproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('caloriecraft.urls')),
    path('', include('accounts.urls')),

    #http(s)://ホスト名/へのアクセスはcaloriecraftの
    #URLconf(urls.py)を呼び出す
    path('', include('caloriecraft.urls')),
    
]

accounts/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser

#from .models import CustomUser

# Create your models here.

class CustomUser(AbstractUser):
    # 追加のフィールドを定義（例）
    age = models.IntegerField(null=True, blank=True)

caloriecraft/models.py
from django.db import models
from .models import CustomUser

class Recipe(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField(max_length=255,null=True)
    author = models.CharField(max_length=100)
    posted_at = models.DateTimeField(auto_now_add=True)
    category = models.CharField(max_length=100, blank=True, null=True)
    image = models.ImageField(upload_to='recipe_images/', blank=True, null=True)
    calories = models.FloatField(blank=True, null=True)
    protein = models.FloatField(blank=True, null=True)
    fat = models.FloatField(blank=True, null=True)
    carbs = models.FloatField(blank=True, null=True)
    ingredients = models.TextField(blank=True, null=True)  # カンマ区切りで食材を保存
 
    def __str__(self):
        return self.title

        

class CalorieCraftPost(models.Model):
    
    title = models.CharField(max_length=200)
    content = models.TextField(max_length=255,null=True)
    image = models.ImageField(upload_to='post_images/', blank=True, null=True)
 
    def __str__(self):
        return self.title
    
class Vegetables(models.Model):

    name = models.CharField(max_length=30)
    content = models.TextField(null=True)
    auther = models.CharField(max_length=100)
    posted_at = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='vegetable_images/', blank=True, null=True)
    protain = models.FloatField(blank=True, null=True)
    fat = models.FloatField(blank=True, null=True)
    carbs = models.FloatField(blank=True, null=True)

    def __str__(self):
        return self.name

'''
class User(models.Model):
    user_id = models.AutoField(verbose_name='ユーザID', primary_key=True)
    user_nickname = models.CharField(verbose_name='ユーザネーム', max_length=50, null=False, unique=True)
    email = models.CharField(verbose_name='メールアドレス', max_length=254, null=False)
    sex = models.IntegerField(verbose_name='性別', null=False)
    birthday = models.DateField(verbose_name='生年月日', null=True)
    password = models.CharField(verbose_name='パスワード', max_length=30, null=False)
    tell_number = models.CharField(verbose_name='電話番号', max_length=21, null=True)

    class Meta:
        db_table = '01_user'  # 明示的にテーブル名を指定



class Recipe(models.Model):
    recipe_name = models.CharField(verbose_name='レシピ名', max_length=25, null=False)
    creator_name = models.ForeignKey('User', verbose_name='レシピ名', on_delete=models.CASCADE)
    step = models.CharField(verbose_name='手順', max_length=255, null=False)
    recipe_id = models.AutoField(verbose_name='レシピID', primary_key=True)

    class Meta:
        db_table = '03_recipes'  # 明示的にテーブル名を指定
'''
class PhotoPost(models.Model):
    user = models.ForeignKey(
        CustomUser
        , verbose_name='ユーザー'
        , on_delete= models.CASCADE  
    )


    title = models.CharField(
        verbose_name= 'タイトル'
        , max_length=100
    )

    comment = models.TextField(
        verbose_name='コメント'
    )

    image1= models.ImageField(
        verbose_name='イメージ１'
        ,upload_to='photos'
    )

    image2 = models.ImageField(
        verbose_name='イメージ２'
        ,upload_to='photos'
        ,blank= True
        ,null=True
    )

    posted_at = models.DateField(
        verbose_name='投稿日時'
        ,auto_now_add=True
    )

    def __str__(self):
        return self.title

accounts/forms.py
from django import forms
from django.contrib.auth.models import User

class UserCreationForm(forms.ModelForm):

    class Meta:
        model = User 
        fields = ('username',)

from django.contrib.auth.forms import UserCreationForm

from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):

    model = CustomUser

    fields = ('username','email','password1','password2')

caloriecraft/forms.py
from django.forms import ModelForm
from .models import Recipe

class RecipePostForm(ModelForm):

    class Meta:

        model = Recipe
        fields = ['title', 'content','image', 'calories', 'protein', 'fat', 'carbs', 'ingredients']

accounts/views.py
from django.shortcuts import render, redirect
from django.views.generic import CreateView, TemplateView
from .forms import CustomUserCreationForm
from django.urls import reverse_lazy
# from .forms import UserRegistrationForm
from django.contrib import messages

class SignUpView(CreateView):
  form_class = CustomUserCreationForm

  template_name = 'signup.html'

  success_url = reverse_lazy('accounts:signup_success')

  def form_valid(self, form):

    user = form.save()
    self.object = user

    return super().form_valid(form)

class SignUpSuccessView(TemplateView):
 template_name = 'signup_success.html'
 
 

caloriecraft/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, ListView
from django.views.generic import TemplateView
from django.views.generic import CreateView
from django.urls import reverse_lazy
from .forms import RecipePostForm
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required

from .models import Recipe
from .models import PhotoPost
# 修正: きちんと IndexView を定義
class IndexView(TemplateView):
    template_name = 'index.html'

@method_decorator(login_required, name='dispatch')

class CreateRecipeView(CreateView):

    form_class = RecipePostForm
    template_name = "post_recipe.html"
    success_url = reverse_lazy('recipe:post_done')

    def form_valid(self, form):

        postdata = form.save(commit=False)
        postdata.user = self.request.user
        postdata.save()
        return super().form_valid(form)
 
def search(request):
    query = request.GET.get('q', '').strip()
    print(f"検索クエリ: {query}")  # コンソールに出力
 
    if not query:
        return render(request, 'caloriecraft/index.html', {'error': '検索クエリを入力してください。'})
 
    # タイトルに検索クエリを含むレシピを取得
    results = Recipe.objects.filter(title__icontains=query)
    print(f"検索結果数: {results.count()}")  # 結果数を出力
 
    for result in results:
        print(f"見つかったレシピ: {result.title}")  # 各結果のタイトルを出力
 
    return render(request, 'caloriecraft/search_results.html', {
        'query': query,
        'results': results
    })
 
class IndexView(ListView):
    template_name = 'index.html'
    queryset = PhotoPost.objects.order_by('-posted_at')
    paginate_by = 9
class PostSuccessView(TemplateView):

    template_name = 'post_success.html'

accounts/templates/signup.html
{% for error in fields.errors %}
  <p style='color: red'>{{ error }}</p>
{% endfor %}

{% extends 'base.html' %}

{% block title %}sign up{% endblock %}

  {% block conents %}

<hr>
<div class= 'container'>
  <div class='row'>

    <div class='col offset-2'>
      <h3>サインアップ</h3>

      <form method = 'post'>
        {% csrf_token %}

        {% for field in form %}
        <p>

          {{ field.label_tag }}<br>

          {{ field }}

          {% if field.help_text %}
           <small style='color: grey'>{{ field.help_text }}</small>
          {% endif %}

          {% for error in field.errors %}
           <p style='color: red'>{{ error }}</p>
          {% endfor %}
      </p>
      {% endfor %}
        <p style='color:red'>
          ※メールアドレスはパスワードをリセットする際に必要になりますので、登録をお願いします。
        </p>

        <input type='submit' value='sign up'>
      </form>

      <br>
      <p><a href='{% url 'photo:index' %}'>
        登録をやめてトップページに戻る</a>
      </p>
    </div>
  </div>
</div>
{% endblock %}

accounts/templates/signup_success.html
{% extends 'base.html' %}

{% block title  %}Registration Complete{% endblock %}

{% block contents %}

<div class='container'>

  <div class='row'>

    <div class='col pffset-4 py-4'>
      <h3>登録が完了しました</h3>

      <p><a href='#'>ログインはこちら</p>
      <!-- #の部分はログイン先のURL -->
    </div>
  </div>
</div>
{% endblock %}

caloriecraft/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>{% block title %}{% endblock %}</title>
        <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="{% url 'caloriecraft:index' %}">Calorie Craft</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="post.html">レシピ登録</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="ai.html">食材認識・レシピ提案</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="logout.html">ログアウト</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="contact.html">お問い合わせ</a></li>
                    </ul>
                </div>
            </div>
        </nav>
       
       
        <!-- Page Header-->
        <header class="masthead" style="background-image: url({% static 'assets/img/食材.jpg' %})">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1>Calorie Craft</h1>
                            <span class="subheading">AIにレシピを頼んでみよう</span>
                            <!-- 検索バー追加 -->
                                <div class="container my-4">
                                    <form method="get" action="{% url 'caloriecraft:search' %}" class="d-flex">
                                        <input class="form-control me-2" type="search" name="q" placeholder="料理名で検索" aria-label="Search">
                                        <button class="btn btn-primary" type="submit">検索</button>
                                        <!-- ナビゲーションメニュー -->
                                        <li><a href =''{% url 'accounts:signup' %}
                                            class='text-white'>サインアップ</a></li>
                                        
                                    </form>
                                </div>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Main Content-->
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    {% for record in orderby_records %}
                    <!-- Post preview-->
                    <div class="post-preview">
                        <a href="{% url 'caloriecraft:post_detail' record.id %}">
                            <h2 class="post-title">{{ record.title }}</h2>
                            <h3 class="post-subtitle">
                                <span style="font-size : 14pt">
                                    {{ record.content|truncatechars:50 }}
                                </span>
                            </h3>
                        </a>
                        <p class="post-meta">
                            Posted by
                            <a href="#!">{{ record.author }}</a>
                            {{ record.posted_at }}に投稿
                            {{ record.category }}
                        </p>
                    </div>
                    <!-- Divider-->
                    <hr class="my-4" />
                    {% endfor %}
                   
                    <!-- Pager-->
                    <div class="d-flex justify-content-end mb-4"><a class="btn btn-primary text-uppercase" href="#!">Older Posts →</a></div>
                </div>
            </div>
        </div>
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="{{ twitter_url }}">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="{{ facebook_url }}">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="{{ github_url }}">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Calorie Craft 2024</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>
 
 

caloriecraft/templates/index.html
{% extends 'base.html' %}

{% block title %}Calorie Craft{% endblock %}

    {% block contents %}
    {% include "recipe_list.html" %}
    {% include "pagination.html" %}


    {% endblock %}

caloriecraft/templates/pagination.html
<ul class="pagination" style="justify-content:center">
    
    {% if page_obj.has_previous %}
    <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
        </a>
    </li>
    {% endif %}
    
    {% for num in page_obj.paginator.page_range %}

    {% if page_obj.number == num %}
    <li class="page-item active">
        <span class="page-link">{{ num }}</span>
    </li>
    {% else %}
    <li class="page-item">
        <a class="page-link" href="?page={{ num }}">{{ num }}</a>
    </li>
    {% endif %}

    {% endfor %}

    {% if page_obj.has_next %}
    <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
        </a>
    </li>
    {% endif %}
</ul>

caloriecraft/templates/post_recipe.html
{% extends 'base.html' %}

{% block title %}Post{% endblock %}

    {% block contents %}
    <br>
    <div class="container">
        <div class="row">
            <div class="col offset-2">

                <form method="POST"
                    enctype="multipart/form-data">
                {% csrf_token %}
                <table>
                    <tr>
                        <th>タイトル</th>
                        <td>{{ form.title }}</td>
                    </tr>
                    <tr>
                        <th>手順</th>
                        <td>{{ form.contents }}</td>
                    </tr>
                    <tr>
                        <th>画像</th>
                        <td>{{ form.image }}</td>
                    </tr>
                    <tr>
                        <th>カロリー数</th>
                        <td>{{ form.calories }}</td>
                    </tr>
                    <tr>
                        <th>タンパク質</th>
                        <td>{{ form.protein }}</td>
                    </tr>
                    <tr>
                        <th>脂質</th>
                        <td>{{ form.fat }}</td>
                    </tr>
                    <tr>
                        <th>炭水化物</th>
                        <td>{{ form.carbs }}</td>
                    </tr>
                    <tr>
                        <th>材料</th>
                        <td>{{ form.ingredients }}</td>
                    </tr>
                </table>
                <hr>
                <button type="submit">登録</button>
                </form>
            </div>
        </div>
    </div>
    {% endblock %}

caloriecraft/templates/post_success.html
{% extends 'base.html' %}

{% block title %}Post Success{% endblock %}

    {% block contents %}

    <br><br>
    <div class="container">
        <div class="row">
            <div class="col offset-2">
                <h4>登録が完了しました。</h4>
            </div>
        </div>
    </div>
    {% endblock %}

caloriecraft/templates/recipe_list.html
  <div class="album py-5 bg-light">
    <div class="container">

      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {% for record in object_list %}
        <div class="col">
          <div class="card shadow-sm">
            <img src="{{ record.image1.url }}" class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title>
            <rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text>
          </img>

            <div class="card-body">
              <p class="card-text">{{record.title}}</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary" onclick="location.href='{% url recipe_detail record.pk %}'">View</button>
                  <button type="button" class="btn btnsm btn-outline-secondary" onclick="location.href='{% url recipe_cat category=record.category.id %}'">{{record.category.title}}</button>
                </div>
                <a href="#"><small class="text-muted">{{record.user.username}}</small></a>
                
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>

caloriecraft/templates/recipe_title.html
    
        <section class="py-5 text-center container">
            <div class="row py-lg-5">
                <div class="col-lg-6 col-md-8 mx-auto">
                    <h1 class="fw-light">photo Gallery</h1>
                    <p class="lead text-muted">
                        ダイエット
                    </p>
                    <p>
                        <a href="#" class="btn-primary my-2">今すぐサインアップ</a>
                        <a href="#" class="btn-secondary my-2">ログイン</a>
                    </p>
                </div>
            </div>
        </section>